 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:4545
 * Running on http://128.199.161.69:4545
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 707-064-028
36.77.35.101 - - [19/Apr/2025 06:57:10] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/streamhib/app.py", line 38, in index
    return render_template('index.html', status=live_status, videos=videos, scheduled=scheduled_streams, inactive=inactive_sessions, stats=stats)
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.10/dist-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 96, in _get_source_fast
    return loader.get_source(environment, template)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/loaders.py", line 215, in get_source
    contents = f.read()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 8459: invalid start byte
36.77.35.101 - - [19/Apr/2025 06:57:10] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
36.77.35.101 - - [19/Apr/2025 06:57:10] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
36.77.35.101 - - [19/Apr/2025 06:57:10] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/root/streamhib/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 707-064-028
